// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import ConfirmAlertController from "./confirm_alert_controller"
application.register("confirm-alert", ConfirmAlertController)

import FlashAlertController from "./flash_alert_controller"
application.register("flash-alert", FlashAlertController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HomeFooterController from "./home_footer_controller"
application.register("home-footer", HomeFooterController)

import MapController from "./map_controller"
application.register("map", MapController)

import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)

import TomselectController from "./tomselect_controller"
application.register("tomselect", TomselectController)

import TypedJsController from "./typed_js_controller"
application.register("typed-js", TypedJsController)
